# Generated by Django 5.2.4 on 2025-07-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('nid_number', models.CharField(max_length=20, unique=True)),
                ('Father_name', models.CharField(max_length=50)),
                ('Mother_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('nid_front_image', models.ImageField(upload_to='nid_images/')),
                ('nid_back_image', models.ImageField(upload_to='nid_images/')),
                ('selfie_image', models.ImageField(upload_to='selfie_images/')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
