# Generated by Django 5.2.4 on 2025-07-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('officer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('postal_code', models.CharField(choices=[('5174', 'Ramna – 5174'), ('1126', 'Dhanmondi – 1126'), ('9373', 'Shahbag – 9373'), ('7312', 'New Market – 7312'), ('3134', 'Lalbagh – 3134'), ('1337', 'Kotwali – 1337'), ('3456', 'Hazaribagh – 3456'), ('6785', 'Kamrangirchar – 6785')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
