# Generated by Django 5.2.4 on 2025-07-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('station_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='PoliceOfficer',
        ),
    ]
