# Generated by Django 5.2.4 on 2025-07-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, choices=[('dhaka', 'Dhaka'), ('chittagong', 'Chittagong'), ('khulna', 'Khulna'), ('rajshahi', 'Rajshahi'), ('barisal', 'Barisal'), ('sylhet', 'Sylhet'), ('mymensingh', 'Mymensingh'), ('rangpur', 'Rangpur')], max_length=20, null=True),
        ),
    ]
